### ISSUE TITLE
Spring Boot Gradle plugin v1.5.8.RELEASE is not available in Gradle Plugin portal

### ISSUE THREAD

**Issue by radarsh** [spring-projects/spring-boot#10664]
[The docs](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html) say we can use `1.5.8.RELEASE` but this version is [not available in Gradle Plugin Central](https://plugins.gradle.org/plugin/org.springframework.boot), with `1.5.7.RELEASE` being the latest version.

**Comment by snicoll** [comment]
`1.5.8.RELEASE` is not fully released yet (there was no announcement yet). We are not able to synchronize the release with central and the gradle repo. JFrog is investigating the issue.

Sorry about that but it's a temp glitch.

**Comment by snicoll** [comment]
@radarsh I've also fixed the current link for the doc so that it points back to `1.5.7.RELEASE` for the time being

**Comment by radarsh** [comment]
@snicoll thanks for this. Will it take a while for the documentation update to be refreshed? Currently I still see the old version.

**Comment by snicoll** [comment]
@radarsh good catch thanks. We have an automated process to update the links based on the latest version. That script overrode my change. I've moved the doc for `1.5.8` to a separate location. Should be good now. Thanks for getting back to us!
