### ISSUE TITLE
Receive Long collection in MessageMapping

### ISSUE THREAD

**Issue by Jhovanni** [spring-projects/spring-boot#11227]
When you try to receive a collection of Long values, as parameter of a MessageMapping method (from spring messaging), you can print the collection. But if you try to access its values, there is an exception throw about not being able to cast Integer to Long.

Replicate it is easy:
```java
@MessageMapping("/channel")
    public void receiveLongs(List<Long> list) {
        for (Long value : list) {
            System.out.println("Line above throws java.lang.ClassCastException");
        }
}
```

Exception throw is java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

Spring boot version: 1.5.8.RELEASE

*Probably the bug is not related to spring boot, but I wasn't able to find where to report it for spring framework project. Please if its required to move it just let me know and I will without any problem. I just need to know where to report it.*

**Comment by snicoll** [comment]
> Probably the bug is not related to spring boot

Indeed, please raise an issue in [Spring Framework issue tracker](https://jira.spring.io/browse/SPR). Rather than a code snippet, please attach a sample that we can run and how you reproduced the issue. Thank you.

**Comment by wangnanyang** [comment]
I suffered the same problem. Can you attach a link to the solution? Thank you.

**Comment by wilkinsona** [comment]
This is the Spring Framework issue that was opened: https://github.com/spring-projects/spring-framework/issues/20799.

**Comment by wangnanyang** [comment]
I know why. thank you.  I'm using Springboot 1.5.9 now. The cost of updating is very high. Besides the method in the link, how can I solve this problem?

**Comment by wilkinsona** [comment]
In addition to being fixed in Spring Framework 5.0.x, the fix was back-ported to 4.3.14 which is included in Spring Boot 1.5.10. 1.5.10 should be a drop-in replacement for 1.5.9. I would strongly encourage you to upgrade to the latest 1.5.x release which, the time time of writing, is 1.5.19. You should also start preparing to upgrade to Spring Boot 2 as 1.5 will reach the end of its life in August this year.

**Comment by wangnanyang** [comment]
The problem hasn't been solved. I upgraded Springboot to 1.5.10 and the version that relies on spring-web packages to 4.3.14, but I still can't. Do you need any other configuration?

**Comment by wilkinsona** [comment]
Please open a new Spring Framework issue with a minimal sample that reproduces the problem.
