### ISSUE TITLE
1.5.x snapshot doc no longer published

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14627]
The doc for `1.5.17.BUILD-SNAPSHOT` is not published, yet CI ran a few times already.

**Comment by wilkinsona** [comment]
It's due to Artifactory mangling the properties on the docs artifact and putting them in the filename instead. Things like this: `spring-boot-docs-1.5.17.BUILD-20180920.082652-5.zip;zip.type=docs;zip.deployed=false `.

**Comment by snicoll** [comment]
Good point, I forgot about that stuff. I'll fix the filenames once the build has completed and circle back with @trevormarshall about the fix we should get from JFrog.

**Comment by trevormarshall** [comment]
We have a snapshot fix from JFrog staged. We are waiting until after the conference to promote it to the production Bamboo master.

**Comment by wilkinsona** [comment]
Looks good now. We have docs for 1.5.17 snapshots again: https://docs.spring.io/spring-boot/docs/1.5.17.BUILD-SNAPSHOT/reference/htmlsingle/. Thank you, @trevormarshall.

**Comment by snicoll** [comment]
@wilkinsona just to triple check here. As I've indicated above, I've fixed the metadata for build #9 manually which should have triggered the doc deployment. 

I can see that build #10 is also broken as before so I am not sure if we've validated that the issue is fixed. I've just triggered build #11 to see if the metadata are correct.

**Comment by wilkinsona** [comment]
Oh, I thought you fixed the filenames on 27 September. Build 9 was published on 1 October, but I see that the problem's still there with build 10 so I guess it isn't fixed after all.
