### ISSUE TITLE
ConfigFileApplicationListener filtering fails when the defaultPropertySource is a composite

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-projects/spring-boot#17011]
Prior to Boot 2.2.0 if you used `spring-cloud-starter` and within your `bootstrap.yml` set `spring.config.name` Boot would correctly load the property file specified in the property.  Starting with Boot 2.2.0 this no longer works.

I have traced the breaking change down to [this line](https://github.com/spring-projects/spring-boot/blob/e481eccd577fd7dcee9c02c20fd10c60b762bf7d/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L356) added in commit d92c2f70230a6e30ccb5d5b51315062505ff74b6

In the situation I described above `defaultProperties` is actually an instance of `ExtendedDefaultPropertySource` defined [here](https://github.com/spring-cloud/spring-cloud-commons/blob/316040ee940e19c6da8eea86d4402571ba3cc010/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L418).

The `sources` property, which is a composite, contains the value of `spring.config.name` in this case.  However in `ConfigFileApplicationListener.replaceDefaultPropertySourceIfNecessary` the code just calls `.getSource` to construct the new `defaultProperties` so we loose the properties in the composite and therefore the `spring.config.name` property is never retrieved.

For a sample that reproduces the problem you can look at [this test](https://github.com/spring-cloud/spring-cloud-core-tests/blob/master/bootstrap/src/test/java/demo/BootstrapClientApplicationTests.java).

**Comment by philwebb** [comment]
See #15445

**Comment by ryanjbaxter** [comment]
@philwebb I read the issue, but that is all about profiles, this problem has nothing to do with profiles.

To add to this, I also think these changes broke this functionality as well, which does have to do with profiles
https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java#L375

**Comment by wilkinsona** [comment]
@ryanjbaxter The commit that you referenced fixed the issue that Phil referenced.

**Comment by philwebb** [comment]
@ryanjbaxter I just added a link to the issue referenced in commit d92c2f70230a6e30ccb5d5b51315062505ff74b6

**Comment by ryanjbaxter** [comment]
@wilkinsona @philwebb sorry I misinterpreted what you were saying ;)

**Comment by philwebb** [comment]
@ryanjbaxter I tried to run [`BootstrapClientApplicationTests`](https://github.com/spring-cloud/spring-cloud-core-tests/blob/master/bootstrap/src/test/java/demo/BootstrapClientApplicationTests.java) but the test passed for me so I'm not sure what I'm doing wrong. Any hints?

For `BootstrapConfigurationTests` it appears that the bootstrap `local.properties` are defining a `spring.profiles.active` key which we are now actively filtering out. I'm not really sure how we can fix this one and also fix ##15445. They seem to be at odds with each other. Is there any reason that the bootstrap context needs to use a property source named `defaultProperties`? If it does, perhaps we need to offer a way to switch off the filtering just for that bootstrap context.

**Comment by ryanjbaxter** [comment]
@philwebb did you remove the `@Ignore` on the test in `BootstrapClientApplicationTests`?

> Is there any reason that the bootstrap context needs to use a property source named defaultProperties? 

@spencergibb @dsyer do you know?  I am a little unsure.

**Comment by spencergibb** [comment]
I'm not sure either.

**Comment by philwebb** [comment]
> `@Ignore` on the test  

Doh! 🤦‍♂

**Comment by philwebb** [comment]
Actually, even with the `@Ignore` removed it appears to work

**Comment by ryanjbaxter** [comment]
Weird not sure, it is failing for me on my machine

**Comment by mbhave** [comment]
I'm able to reproduce this. It's because we use `defaultProperties.getSource()` [here](https://github.com/spring-projects/spring-boot/blob/16c521a9e6344c248ee474a4ef101996dd9c3659/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L356). The `ExtendedDefaultPropertySource` used by Spring Cloud has the property sources wrapped inside a `CompositePropertySource` and `defaultProperties.getSource()` just returns an empty map. We could change the filtering logic so that it only applies to Spring Boot's default property source somehow.

**Comment by philwebb** [comment]
@ryanjbaxter I've implemented the fix suggested by @mbhave, both Spring Cloud tests referenced in this issue work for me locally now.

**Comment by ryanjbaxter** [comment]
@philwebb I removed the `@Ignore` in `BootstrapConfurationTests` but the build still fails using Snapshots (I am going to add it back so we have a green build for now).
https://jenkins.spring.io/job/spring-cloud-commons-master-ci/8853/testReport/org.springframework.cloud.bootstrap.config/BootstrapConfigurationTests/includeProfileFromBootstrapProperties/

**Comment by wilkinsona** [comment]
FWIW, it also fails for me when built locally with `./mvnw -U clean verify`.

**Comment by mbhave** [comment]
Looks like I was wrong about the same fix being able to fix both tests. I share what @philwebb said here:

> I'm not really sure how we can fix this one and also fix 15445.

**Comment by philwebb** [comment]
I swear it worked in my IDE :/

I've opened #17141 to look at the failing test. It feels like a different issue and the composite property source problem has been fixed so let's keep this issue just for that one.
