### ISSUE TITLE
Workaround SUREFIRE-1679 junit-platform-launcher dependency issue

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17517]
Triggered by #17491 we've discovered that surefire has a bug which means we cannot directly depend on `junit-platform-launcher`. Until it's fixed, we'll need to use reflection.

**Comment by wilkinsona** [comment]
I've raised [SUREFIRE-1679](https://issues.apache.org/jira/browse/SUREFIRE-1679).

**Comment by dreis2211** [comment]
You are awesome

**Comment by dreis2211** [comment]
@wilkinsona Could be that this is already fixed via https://issues.apache.org/jira/browse/SUREFIRE-1585

**Comment by wilkinsona** [comment]
I'm not sure. I've tested with both 3.0.0-M3 and 3.0.0-SNAPSHOT and the problem still occurs. Unfortunately, 3.0.0-SNAPSHOT resolves to 3.0.0-20190214.112538 so I'm missing out on 5 months of changes. The code that I believe is problematic is [still there in master](https://github.com/apache/maven-surefire/blob/2d0992771b501bf8ac3adb4f07057d57802a1dfa/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L1788-L1794) so my suspicion is that the problem still exists.
