### ISSUE TITLE
liquibase-core leaks the classloader

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2279]
Originally reported as spring-io/platform#128:

> See [CORE-2182](https://liquibase.jira.com/browse/CORE-2182) for details.
> 
> Is there documentation as to how the platform bom is tested?
> 
> I have test code that checks for classloader leaks. Maybe it can be integrated to prevent issues like this in future (even for other dependencies).

**Comment by philwebb** [comment]
@ArloL We'd be very interested in the test code to check for leaks if you can share it?

**Comment by philwebb** [comment]
@wilkinsona Should we consider downgrading liquibase?

**Comment by ArloL** [comment]
Basically I use an embedded tomcat with a weak reference to the WebAppClassLoader and see whether it is collected properly. The principle can be seen in [this old jUnit test](http://www.kopfnickerchen.de/articles/2013-07-27-automatically-test-classloader-memory-leaks.html).

I have a newer version that works around some issues. I'll post it tomorrow with a proper license.

**Comment by philwebb** [comment]
Fantastic, thanks. Have you signed the CLA?

**Comment by wilkinsona** [comment]
The problem's been fixed in 3.3.2. There's no release date for it yet.

**Comment by ArloL** [comment]
3.3.2 has been released. But the problem was not fixed correctly.

**Comment by ArloL** [comment]
@philwebb I just open sourced our test for classloader leaks: https://github.com/evosec/tomcat-classloader-leak-test

**Comment by ArloL** [comment]
This issue can be closed since we started using https://github.com/mjiderhamn/classloader-leak-prevention which executes the shutdown hooks.
