### ISSUE TITLE
build-info.properties is generated in a different path causing errors with BuildProperties bean

### ISSUE THREAD

**Issue by AlbertoCortina** [spring-projects/spring-boot#30148]
**Versions used**
Spring boot 2.6.4
Java 17
Gradle 7.4

**Description of the bug**
Starting from Spring boot 2.6.4 the _build-info.properties_ file is generated in a different path causing the application to fail when it's deployed in a servlet container and you are using a _BuildProperties_ bean.

```
demo_264-app-1  |       Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'helloWorldController' defined in file [/usr/local/tomcat/webapps/demo/WEB-INF/classes/com/example/demo/HelloWorldController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.info.BuildProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

Structure of the war using Spring boot 2.6.4
![image](https://user-images.githubusercontent.com/22643509/157516202-2e56077f-9461-414d-8d9b-3f3be9c574a1.png)

Structure of the war using Spring boot 2.6.3
![image](https://user-images.githubusercontent.com/22643509/157516082-0bf8bea0-0d9f-4a1c-85c3-d54f5741787e.png)

**How to reproduce the error**
[demo_2.6.4.zip](https://github.com/spring-projects/spring-boot/files/8217856/demo_2.6.4.zip)
[demo_2.6.3.zip](https://github.com/spring-projects/spring-boot/files/8217857/demo_2.6.3.zip)

Download both projects (basically they are the same project just changing the Spring boot version) and run the following command in both of them. After it finishes you can compare the wars created under _build/libs_ folder and check that the path of the file is different.
```
$ ./gradlew bootWar
```

Also, to check the error produced when you run the war created by the project on a servlet container, you can find a docker-compose file that you can execute after generating the wars, and you will see the error at startup on the version using Spring boot 2.6.4
```
$ ./gradlew bootWar
$ docker compose up
```
![image](https://user-images.githubusercontent.com/22643509/157528428-80f98eb8-c669-4da9-a200-aff7a90d9283.png)

**Comment by wilkinsona** [comment]
Sorry for the inconvenience. This has already been fixed in the latest 2.5 and 2.6 snapshots.

Duplicates https://github.com/spring-projects/spring-boot/issues/30026.

**Comment by flyingfishflash** [comment]
@wilkinsona Perhaps this is a separate issue, but with spring-boot 2.6.5 and gradle :bootJar, I'm still seeing the behavior where build-info.properties is place in /META-INF rather than /BOOT-INF/classes/META-INF/. 

This cause actuator/info endpoint to return nothing.

**Comment by wilkinsona** [comment]
That would be a separate issue as this issue concerned a war deployed to a Servlet container.

The properties file is loaded from `classpath:META-INF/build.properties`. Both the root of the jar and `BOOT-INF/classes` are on the classpath so the file should be found from either location.

If you’d like us to investigate the problem that you are seeing, please open a new issue with a minimal sample that recreates it.
