### ISSUE TITLE
Auto-configuration ignores user-provided ObservationConventions

### ISSUE THREAD

**Issue by braunsonm** [spring-projects/spring-boot#33285]
With the move to micrometer observability, the `WebClientExchangeTagsProvider` and `RestTemplateExchangeTagsProvicer` have both been deprecated in favour of `ObservationConvention`s.

The configuration (in this case the reactive but also affects the servlet) is not customizable enough to allow users to move off the deprecated classes.

The configuration should have means to accept a custom implementation of the `ObservationConvention`. Right now you would have to exclude this configuration class completely as the default convention is created in the bean method. See here:
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/observation/web/client/WebClientObservationConfiguration.java#L53

## Additional Context

I would like to migrate away from deprecated classes, but without being able to create my own `ObservationConvention` I cannot cleanly stop using the old TagsProvider's.

cc @bclozel excuse the tag, but mentioned as you created these configuration classes

**Comment by wilkinsona** [comment]
Brian's been working on a migration guide for this. Does https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Metrics-3.0#migrating-tag-providers-and-contributors help?

**Comment by bclozel** [comment]
@braunsonm no worries.

Does [this section of the migration guide helps](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Metrics-3.0#migrating-tag-providers-and-contributors)? Could you tell us more about your use case and how we could improve it?

**Comment by braunsonm** [comment]
That does help, I was unaware that multiple implementations to the `ObservationRegistry` effectively override the ones provided by Spring Boot.
Thank you, this satisfies my use case.

**Comment by bclozel** [comment]
Thanks!

**Comment by bclozel** [comment]
We've also addressed this in the reference documentation in #33281

**Comment by braunsonm** [comment]
Hey @bclozel We are not seeing it behave the way you describe in the documentation. Would you like a separate issue for this?

With a very simple example:

```java
public class ExtendedClientRequestObservationConvention extends DefaultClientRequestObservationConvention implements
  GlobalObservationConvention<ClientRequestObservationContext> {
  @Override
  public KeyValues getLowCardinalityKeyValues(ClientRequestObservationContext context) {
    // Note the URI has been removed
    return KeyValues.of(method(context), status(context), exception(context), outcome(context));
  }
}
```


```java
@Configuration
public class SampleConfiguration {
  @Bean
  ClientRequestObservationConvention sampleConvention() {
    return new ExtendedClientRequestObservationConvention();
  }
}
```

I can still see that the Default implementation is called, even when the bean is wired up.

**Comment by bclozel** [comment]
Thanks @braunsonm -  we've discussed this with @marcingrzejszczak and found that the current situation is not in line with the migration story we're expecting.
I'm repurposing this issue to use `ObservationConvention` beans provided by the application as a way to customize key values. I've also [updated the migration guide accordingly](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Metrics-3.0). You can test this approach with `3.0.0-SNAPSHOT` as soon as this issue is resolved.
