### ISSUE TITLE
Spring boot 3.1.0 native build (windows exe) won't start

### ISSUE THREAD

**Issue by dick2tick** [spring-projects/spring-boot#35569]
**Environment:**
Windows 11
spring-boot: 3.1.0
kotlin: 1.8.21
native-gradle-plugin: 0.9.22
graalvm: graalvm-ce-java19-22.3.1

**Bug description:**
native compile ends without errors, but when starting the exe version, an error occurs:
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130) ~[na:na]
```
**Regression:**
works fine with spring-boot 3.0.7 and exactly the same environment and code

with each new spring-boot version, the native build does not work !?!

**Comment by wilkinsona** [comment]
This looks like a duplicate of https://github.com/spring-projects/spring-framework/issues/30492. Can you please try with 6.0.10-SNAPSHOT of Spring Framework that is available for https://repo.spring.io/snapshot.

**Comment by dick2tick** [comment]
an error occurs with the patch:
`Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.dialect.DialectLogging (implementation not found in jdk.internal.loader.ClassLoaders$AppClassLoader@45c8e616)`

which is related probably with https://github.com/oracle/graal/issues/5626 and/or https://github.com/oracle/graal/issues/6526

I will start to cry

**Comment by wilkinsona** [comment]
That should be addressed by https://github.com/oracle/graalvm-reachability-metadata/commit/4629271f9249c37cb511a396f9e02b7d471ca64d.

**Comment by edeandrea** [comment]
Thank you again. Using Spring Framework 6.0.10-SNAPSHOT with the graalvm-reachability-metadata 0.3.1 does not fix the problem (still produces the error I posted above). I'll wait for a new Spring Boot version that will hopefully resolve it.
