### ISSUE TITLE
Class loading fails on an interrupted thread causing com.mongodb.event.ServerClosedEvent to fail to load when Mongo detects a cluster change

### ISSUE THREAD

**Issue by manjian14** [spring-projects/spring-boot#38611]
We've encountered a connectivity problem after migrating from Spring Boot 3.1.5/3.1.6 to 3.2.0. The error log points to a missing class:

java.lang.ClassNotFoundException: com.mongodb.event.ServerClosedEvent

This is affecting our connection to MongoDB "AWS DocumentDB." Any guidance or resolution on this matter would be greatly appreciated.

![Opera Snapshot_2023-11-30_121747_us-east-1 console aws amazon com](https://github.com/spring-projects/spring-boot/assets/90276040/c6998be3-31fa-4e0c-aa1b-8f1e90271763)
![Opera Snapshot_2023-11-30_121933_us-east-1 console aws amazon com](https://github.com/spring-projects/spring-boot/assets/90276040/129b4edd-a811-4159-8e0f-606efa954d22)

**Comment by mhalbritter** [comment]
Hello!

I can't see any code from Boot in the stacktrace, besides the JAR loader. I'm not sure if this has something to do with the Uber JAR rewrite. Can you please try with the classic loader implementation and report back if that fixes the issue?

See here for details: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support

**Comment by manjian14** [comment]
Hi 
 With classic loader, seems the issue has been fixed 
 
bootJar {
    archiveFileName = "${rootProject.name}.${archiveExtension.get()}"
    loaderImplementation = LoaderImplementation.CLASSIC
}

**Comment by mhalbritter** [comment]
cc @philwebb

**Comment by wilkinsona** [comment]
@manjian14 The stack trace would suggest that the problem occurs when there's a change in the topology of the cluster but I haven't been unable to reproduce it. Can you please provide a minimal sample and the steps to follow to cause the failure?

**Comment by manjian14** [comment]
I tried using 3.2.1-SNAPSHOT, but ran into a problem—' springboot binaries are incompatible with your platform'

**Comment by wilkinsona** [comment]
What platform are you using? It's rather unfortunate that it apparently won't allow you to test snapshot artifacts.

**Comment by msievers** [comment]
Same thing with `3.2.1-SNAPSHOT`

```
java.lang.NoClassDefFoundError: com/mongodb/event/ServerClosedEvent
	at com.mongodb.internal.connection.DefaultServer.close(DefaultServer.java:172)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.removeExtraHosts(AbstractMultiServerCluster.java:436)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.ensureServers(AbstractMultiServerCluster.java:407)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.handleReplicaSetMemberChanged(AbstractMultiServerCluster.java:248)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.lambda$onChange$3(AbstractMultiServerCluster.java:197)
	at com.mongodb.internal.Locks.lambda$withInterruptibleLock$1(Locks.java:53)
	at com.mongodb.internal.Locks.checkedWithInterruptibleLock(Locks.java:66)
	at com.mongodb.internal.Locks.withInterruptibleLock(Locks.java:59)
	at com.mongodb.internal.Locks.withInterruptibleLock(Locks.java:52)
	at com.mongodb.internal.connection.BaseCluster.withLock(BaseCluster.java:226)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.withLock(AbstractMultiServerCluster.java:54)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.onChange(AbstractMultiServerCluster.java:165)
	at com.mongodb.internal.connection.DefaultSdamServerDescriptionManager.updateDescription(DefaultSdamServerDescriptionManager.java:113)
	at com.mongodb.internal.connection.DefaultSdamServerDescriptionManager.lambda$update$0(DefaultSdamServerDescriptionManager.java:75)
	at com.mongodb.internal.Locks.lambda$withInterruptibleLock$1(Locks.java:53)
	at com.mongodb.internal.Locks.checkedWithInterruptibleLock(Locks.java:66)
	at com.mongodb.internal.Locks.withInterruptibleLock(Locks.java:59)
	at com.mongodb.internal.Locks.withInterruptibleLock(Locks.java:52)
	at com.mongodb.internal.connection.BaseCluster.withLock(BaseCluster.java:226)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.withLock(AbstractMultiServerCluster.java:54)
	at com.mongodb.internal.connection.DefaultSdamServerDescriptionManager.update(DefaultSdamServerDescriptionManager.java:60)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:169)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.mongodb.event.ServerClosedEvent
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:104)
	at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 23 more 
```

**Comment by msievers** [comment]
The errors are gone when using `<loaderImplementation>CLASSIC</loaderImplementation>` with Spring Boot 3.2.0

**Comment by philwebb** [comment]
@msievers Are you able to provide a sample application that we can debug?

**Comment by msievers** [comment]
@philwebb I'll give it a try and ping you once I got it. As I cannot take one of our company apps where I see this happen, I hope it can be reproduced with some simple playground app.

**Comment by ANigam123** [comment]
Hi @msievers I have been facing the similar problem, tried CLASSIC loader implementation but it's still failing. It worked fine with one of my Gradle projects. Can you please share the plugin config ? Thanks.
I tried with : 
  <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <loaderImplementation>CLASSIC</loaderImplementation>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by wilkinsona** [comment]
Thanks very much, @msievers. I've now been able to reproduce the `ClassNotFoundException`.

**Comment by wilkinsona** [comment]
This is another variant of https://github.com/spring-projects/spring-boot/issues/38154, but this time allowing the interruption to continue by rethrowing the `ClosedByInterruptException` is insufficient. We really need to perform the read in an uninterruptible manner. Unfortunately, the JDK's support for that is an implementation detail of `sun.nio.ch.FileChannelImpl` so we'll need to implement our own.

**Comment by philwebb** [comment]
We've just pushed a fix for this. It would be much appreciated if someone could try the latest 3.2.1 SNAPSHOT with the default loader to see if we've fixed the problem.

**Comment by msievers** [comment]
@philwebb I'll give it a try and report back.

**Comment by msievers** [comment]
@philwebb It's still failing with 3.2.1-SNAPSHOT. Was the last CI build completed successfully? It's orange, maybe the changes were not published/pushed, see

https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-3.2.x/jobs/build/builds/802

**Comment by philwebb** [comment]
Gahh, those failures are a pain. It wasn't published but I also didn't get a notification. I've kicked it off again and I'll comment back here when it's done. Sorry about that.

**Comment by philwebb** [comment]
Sorry @msievers, we're having some trouble with our CI right now and we haven't managed to publish jars yet.

**Comment by wilkinsona** [comment]
@msievers Our CI's been fixed and a new snapshot 3.2.1-SNAPSHOT build has been published. Could you please give it a try if you have the time?

**Comment by msievers** [comment]
@philwebb @wilkinsona I can confirm that for my two use cases, one being our internal application and the other the application I created on GitHub to reproduce the error, the issue seems to have disappeared with the use of the current Spring Boot 3.2.1-SNAPSHOT version.

**Comment by wilkinsona** [comment]
Thank you, @msievers. That's some greatly appreciated good news.
