### ISSUE TITLE
Change Tomcat defaults so that save session data is not saved

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#4156]
Test passes on latest 1.2.6, fails on 1.3.0.M5. Steps to reproduce ( i used STS & linux):

    1. Create a web starter project using 1.3.0.M5 ; no devtools or other starters
    2. Add a simple test method to add a session variable
    3. Start the server on either your desktop, or targeted platform (linux)
    4. Hit the endpoint a few times.
    5. restart the container.
    6. hit it again, note the counter continues on

Anything like the following will suffice to test. Another tip if figured out while using Boot: always run with -Djava.io.tmpdir="target" . This will make troubleshooting "hidden" files a lot easier

	@RequestMapping("/addSessionVar")
	public String addSessionVar( HttpSession session)  {
		
		if ( session.getAttribute( SAMPLE_SESSION_VAR ) == null ) session.setAttribute( SAMPLE_SESSION_VAR, new AtomicInteger(0) );
		
		AtomicInteger val =  (AtomicInteger ) session.getAttribute( SAMPLE_SESSION_VAR ) ;
		int curValue = val.incrementAndGet() ;
		
		logger.info( "Updated session variable {} : {}", SAMPLE_SESSION_VAR, curValue ) ;
		
		return "Updated session variable " + SAMPLE_SESSION_VAR + " to: " + curValue ;
	}

**Comment by philwebb** [comment]
I think that you're probably hitting #3851 which has been fixed in the latest SNAPHOTs. 

Trying with M5, if I follow the steps you describe above things work fine as long as `spring-boot-devtools` isn't on the classpath. When it is on the classpath sessions are stored across restarts but unfortunately setting `server.session.persistent=false` has no effect.

Can you try the latest 1.3 SNAPSHOT to see if it fixes your issue?

**Comment by peterdnight** [comment]
I updated to the snapshot - still no luck. As mentioned in original posting - I did not add anything but the web starter.

Couple of notes:
- if you hard kill the process - it will not have a chance to create SESSIONS.ser
- STS ide kill (at the top) does this by default; but if you kill via the console you will see:
2015-10-12 17:07:42.218  INFO 2460 --- [)-10.116.103.98] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2015-10-12 17:07:42.234  INFO 2460 --- [)-10.116.103.98] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown


- to make troubleshooting in STS a littler easer, I added the following into application.properties:
server.tomcat.basedir=target/tomcat
server.session.persistent=false

![stsfile](https://cloud.githubusercontent.com/assets/2165498/10438920/8418904e-7104-11e5-8624-3586af4b0943.png)

**Comment by philwebb** [comment]
Setting `server.tomcat.basedir=target/tomcat` is causing Tomcat to set the `TEMPDIR` servlet attribute to `.../target/tomcat/work/Tomcat/localhost/ROOT`. See `org.apache.catalina.core.StandardContext.postWorkDirectory()`. The in turn causes the `SESSIONS.SER` file to always be written in the same place.

As far as I can tell both Spring Boot 1.2.x and 1.3.x behave in the same way here. 

Does deleting the `server.tomcat.basedir` property make things work as expected?

**Comment by peterdnight** [comment]
1.3.x: removing server.tomcat.basedir does indeed seem to work
1.2.x: leaving it in: works. One difference i noted in the logs in 1.2; the shutdown logs shown above are not output. Is it supposed to show the same deregister messages noted above.

from a managability perspective - my initial thoughts is that burying embedded tomcat under /tmp is a little annoying. eg. we do a kill / clean (rm -rf) on a boot runtime - yet it has some incredibly relevant state being store else where on the FS. Which is why we started looking at this nice param in the first place.

**Comment by philwebb** [comment]
Perhaps we need to offer a `server.session.store-directory` property that could be used in conjunction with `server.session.persistent=true` to store session data in a specific place?

Arguably we should also change Tomcat's `StandardManager` to default with no `pathname`.

**Comment by peterdnight** [comment]
I confirmed that tomcat sets tmpdir to be in current directory (ref. catalina.sh), which for my use case will work for Boot and the use case above if I add -Djava.io.tmpdir="javaTemp"  This does raise some considerations for boot.

Perhaps [reference appendix d](http://docs.spring.io/spring-boot/docs/1.3.0.M5/reference/htmlsingle/#executable-jar-exploded-archives) could be extended a bit to encompass some best practices. Along the lines of the following:

1. Create BOOT_BASE (working folder for Boot process)
2. Create BOOT_BASE/logs/, BOOT_BASE/temp/, BOOT_BASE/jar/
3. Get the jar (we use mvn get),  then extract /usr/bin/unzip -qq -o $serviceName.jar -d jar
4. run as: java  $JAVA_OPTS -Djava.io.tmpdir="temp" -classpath 'jar' org.springframework.boot.loader.JarLauncher --spring.profiles.active=$lifecycle  --server.port=$servicePort >> logs/consoleLogs.txt 2>&1 &
	

I do like the simplicity/elegance of Boot jar packaging, and all the goodness it brings. For targeted deployments - the processes codified in tomcat, and tweaked a bit above provide a (far?) more suitable baseline for running Boot apps in our env; and I suspect most envs. Perhaps it could be called the *java -jar extended* section.

**Comment by peterdnight** [comment]
One other minor item - devTools in non-prod (not just on the desktop)  can be really handy when troubleshooting connection strings and other configuration. Use of the jarLauncher shown above seems to disable; it would be great if we could add --spring.devtools.enable=true for dev/qa ; and omit the param for lt and prod.

**Comment by philwebb** [comment]
@peterdnight re: devtools. Unfortunately initialization happens so early that it's not possible to use `application.properties` to configure it. I'll raise a new issue to add System property support.

**Comment by philwebb** [comment]
@peterdnight Actually the restart element of devtools can't work in a fat jar anyway.
