### ISSUE TITLE
Allow multiple values for management.security.role

### ISSUE THREAD

**Issue by arosini** [spring-projects/spring-boot#5045]
My project uses Spring Security OAuth to authenticate against an LDAP service. The project has several users, all of which need to see full health information. However, they do not share a common a common role in LDAP (which I have no control over). 

I would like to be able to do one of the following (so all users can see the full health information):

1. Specify multiple` management.security.role` values (as a comma separated List like other properties) 

2. Be able to disable the function of the management role, effectively allowing any authenticated user to see the full health information.

I tried setting `management.security.enabled=false`, but then even an unauthenticated user can see the full health information.

I also tried setting `health.sensitive=false`, but without the correct management role, authenticated users still could only see limited health information.

**Comment by philwebb** [comment]
Have you tried setting `endpoints.health.sensitive=false`? That should allow all users to see full health details.

**Comment by philwebb** [comment]
Regardless, adding support for multiple roles would be a nice addition.

**Comment by arosini** [comment]
Yeah I meant `endpoints.health.sensitive=false` when I said `health.sensitive=false`.
That kind of brings up two more issues in my opinion.

1. A non-sensitive endpoint is not accessible by an unauthenticated user (already filed as #5072). I have always gotten around this by setting `security.ignored=/info` etc../

2. A non-sensitive endpoint is restricted based on the management role. This doesn't seem like what the intended behavior was based on the table at https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html#production-ready-health-access-restrictions. It appears the actual behavior is the user needs to be "Authorized" for full content, not just "Authenticated".

I see this was fixed though, thanks!

**Comment by philwebb** [comment]
> I see this was fixed though, thanks!
Which issue was fixed? Number 2) in your list?

Let's keep this issue focused on just adding multiple role support. Could you raise another one with more details of 2).

Do you by any chance have a sample application that demonstrates the problem. I'm wondering if some combination of OAuth and Actuator is causing the issue. We probably don't have explicit tests for that currently.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by arosini** [comment]
I meant the original issue I filed was fixed. I will file another issue for the OAuth/Actuator behavior I have seen. Thanks again!

**Comment by vpavic** [comment]
> I meant the original issue I filed was fixed.

@arosini the original issue is not fixed, I've only created the PR but it's up to Spring Boot team to review it and accept/merge it.

For that reason I'd suggest you to reopen this issue.

**Comment by vpavic** [comment]
I see this is currently scheduled for ```1.4.0.M2```, any chance it also makes the ```1.3.4```?
I've implemented the change in #5074 a while ago.

**Comment by snicoll** [comment]
>  any chance it also makes the 1.3.4?

1.3 is a maintenance release so we won't apply such a change there.

**Comment by snicoll** [comment]
closing in favour of the PR #5074
