### ISSUE TITLE
@ConfigurationProperties locations

### ISSUE THREAD

**Issue by Delwing** [spring-projects/spring-boot#6726]
Question

Hey,
Before Spring Boot 1.4 I've been using `@ConfigurationProperties` to configure simmilar beans with different properties.
Example:

```java
@Configuration
public class TagConfiguration {

    @Bean(name = "restrictive")
    @ConfigurationProperties(locations = "classpath:whitelist-restrictive.yml")
    public TagProviderConfiguration tagProviderConfigurationLevel0() {
        return new TagProviderConfiguration();
    }

    @Bean(name = "basic")
    @ConfigurationProperties(locations = "classpath:whitelist-basic.yml")
    public TagProviderConfiguration tagProviderConfigurationLevel1() {
        return new TagProviderConfiguration();
    }

}
```

Now, not only this code does not compile, since prefix is duplicated, but also `locations` param is deprecated.

So is there any way to achieve similar result but without using prefixes? I just want to have very similar configuration files to configure multiple beans.

**Comment by snicoll** [comment]
We want to promote the use of a consistent `Environment`. You could have both the `restrictive.*` and `basic.*` keys to be defined in the environment. There's really no need to have separate files for that.

If, for some reasons, you want to have that configuration separate in custom files, you can use the `spring.config.location` attribute to [define where Spring Boot should load its configuration](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files).

We don't think that having one bean tied to one source file is a good thing. There's some nice content in this comment as well: https://github.com/spring-projects/spring-boot/issues/6220#issuecomment-228412077

**Comment by Delwing** [comment]
This is very inconvenient, since configuration like white-lists can be very long and adding keys feels like "polluting" config file. I guess PropertiesConfigurationFactory with YamlPropertiesFactoryBean will do the trick in that case.

**Comment by OrangeDog** [comment]
I have one single class that loads its data from an external yaml file, unrelated to the application environment. `@ConfigurationProperties(location = )` was perfect for this.

What exactly am I supposed to replace this with, without polluting the global environment or exposing the implementation requirements of this class?

**Comment by snicoll** [comment]
This issue is closed and I think I already replied to that question. If that's not enough, please ask on stackoverflow.

**Comment by gabrieledarrigo** [comment]
@OrangeDog how do you solved?

**Comment by Zubastick** [comment]
That's how I fixed it:

`public class YamlPropertySourceFactory implements PropertySourceFactory {

    @Override
    public PropertySource<?> createPropertySource(String name, EncodedResource resource) throws IOException {
        return name != null ? new PropertySourcesLoader().load(resource.getResource(), name, null) : new PropertySourcesLoader().load(
                resource.getResource(), getNameForResource(resource.getResource()), null);
    }

    private static String getNameForResource(Resource resource) {
        String name = resource.getDescription();
        if (!StringUtils.hasText(name)) {
            name = resource.getClass().getSimpleName() + "@" + System.identityHashCode(resource);
        }
        return name;
    }
}`

Mark your properties class:
@PropertySource(value = "classpath:someyml.yml", factory = YamlPropertySourceFactory.class)
@ConfigurationProperties("prefix")

**Comment by fanyaoxuan** [comment]
@Zubastick    I want to get the array through @value，But they never get it
   `@Value("${shiro.oauths}")
    private String[] oauths;`

**Comment by Tianhao25** [comment]
I still don't get this...Why using _locations_ in configurationproperties is bad? It took me so much time to find an alternative solution...

**Comment by MisterSpicy** [comment]
I get the desire to reduce code smell and advocate for a clean environment, but few of us work in such nice environments, and often we don't get to choose how our configurations are handed to us.

I really hope Spring brings it back in a future release!

**Comment by kaifuu** [comment]
Hi,@Zubastick 
If your convenient, could your help me take a look? many thanks.
I used YamlPropertySourceFactory, it need to append spring-boot.1.5.4.RELEASE in pom.xml. 
When the program is run, the following exception occurs.

2018-08-29 16:49:14.644 ERROR [main] org.springframework.boot.SpringApplication:771 - Application startup failed                
java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/bind/Binder

**Comment by webfolderio** [comment]
Spring sucks!
