### ISSUE TITLE
Provide configuration property metadata for binding to Map<String, RichType> and List<RichType>

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9945]
One example of such a `Map` is [in Spring Cloud stream](https://github.com/spring-cloud/spring-cloud-stream/blob/bd002e4aaf05f2f4e31cb09d706910b470f960a3/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceProperties.java#L60-L61).  As things stand, there's no metadata for any of the properties on `BindingProperties`. I think it would be interesting to explore the possibility of providing metadata for those properties, perhaps using a wildcard for the key in the map:

```
spring.cloud.stream.bindings.*.content-type
spring.cloud.stream.bindings.*.destination
spring.cloud.stream.bindings.*.group
…
```

For this to be useful, we'd need a corresponding enhancement in each of the IDE plugins.

**Comment by snicoll** [comment]
I've thought long and hard about this and I don't think we should do this. There are several reasons:

1. Scalar vs. Group: the only way for us to harvest nested object is by using `@NestedConfigurationProperty` (essentially, this is not a scalar value, please create a "sub-group" for all the properties defined by that type). If we support that for collections or maps now, how do we tell if the value is scalar or not?
2. Scope: if we find a way to fix this and we offer automatic harvesting of POJOs, where do we stop? The next step is to expect this to be somehow recursive (`BindingProperties` may hold another nested object).
3. Duplication: the use of the `*` above is what I ended up considering myself but that pojo can be used in multiple places, in multiples maps and/or in different objects. It means that the metadata is duplicated. If you don't want that, we need a third root objects (to harvest the pojo) and a way to reference to it somehow).

Let's see what the rest of the team thinks.

**Comment by philwebb** [comment]
For "1)" the `@NestedConfigurationProperty` could be the indicator that the value isn't a scalar. So  `@NestedConfigurationProperty Map<String, Foo>` is a hint that `Foo` can be expanded with the `*` syntax, where as `@NestedConfigurationProperty Map<String, Foo>` cannot (and we expect to be able to convert a `String` to a `Foo` somehow.

For "2)" and "3)" I'd probably go with duplicate `*`. I don't see the duplication being all that much of a problem, as long as there isn't an infinite loop (e.g. `Foo` contains a `Map<String,Foo>`).

**Comment by philwebb** [comment]
FWIW, I think we shouldn't invest too much time thinking about this until after 2.0.

**Comment by snicoll** [comment]
> and we expect to be able to convert a String to a Foo somehow.

That would break backward compatibility but I think having to add an annotation to ask the AP to "expand" is a nice way to solve the scope problem. Great idea! So 1) and 2) could be fixed by some signals that the AP should expand the metadata (and the binding should work as it does now, regardless of the annotation). That's pretty much what happens today for `@NestedConfigurationProperty` anyway.

As for 3, duplication is much easier but we need some feedback from IDE developers first IMO (ping @yanncebron @kdvolder and @AlexFalappa).

**Comment by wilkinsona** [comment]
Since this issue was raised, the IDEs have plugged the gap to varying degrees. A new gap will appear if we add support for immutable configuration properties that use constructor injection. Without metadata, they'd have to plug that gap and look at the constructor rather than the property setters to figure out what properties to offer.

**Comment by rwinch** [comment]
@wilkinsona Perhaps I am missing something, but I haven't seen any improvements with this from a Spring Security standpoint. For example:

```
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            |
```

I get no auto complete at | (pretend that is the cursor). This is something that I would really like for users.

Can you point me to how the IDE's have plugged the gap?

**Comment by snicoll** [comment]
I can't speak for Eclipse but IJ has support for this for ages on `.properties`. There isn't for yaml at the moment though. To be clear, we're now considering this with higher priority given the potential binding change.

**Comment by rwinch** [comment]
Thanks for the clarification @snicoll. I wasn't aware that .properties were supported by IntelliJ. Also glad to hear that this means this is a higher priority. I had misunderstood it to mean that the IDE already was taking care of the issue.

**Comment by kdvolder** [comment]
Should work in Eclipse / STS, in `.yml` as well as `.properties`. If it doesn't for your particular example please raise a bug with [STS4](https://github.com/spring-projects/sts4/issues).

**Comment by kdvolder** [comment]
@rwinch I couldn't get your specific example to work (presumably because I don't have the right stuff on the project's classpath). But here's a similar example, to show how it is (supposed to) work:

https://drive.google.com/open?id=1bfzAdMMV6Oi148yXxEvaKvAfxqTR4nM6

Do let us know by raising a STS bug if you find problems with your actual example.

**Comment by rwinch** [comment]
Thanks @kdvolder! I will have to give it a try in the latest STS.

PS: The dependency you need is org.springframework.boot:spring-boot-starter-oauth2-client

**Comment by mhalbritter** [comment]
This file is read by the `spring-boot-properties-migrator` too, to notify users of deprecations in the property names and on-the-fly rewriting. It would be great if this a) would support for map-based types (i stumbled over `spring.security.saml2.relyingparty.registration.*.identityprovider`) and b) would support wildcards to make renamings simpler (e.g. `management.metrics.*` to `management.*.metrics`).

**Comment by wilkinsona** [comment]
The lack of this metadata allowed the mistake that @dreis2211 has fixed in [this pull request](https://github.com/spring-projects/spring-boot/pull/31845) to slip through. Our Asciidoctor extension only validates maps on a best-effort basis. The prefix, `spring.security.saml2.relyingparty.registration`, matched and there's no metadata to tell it what properties each entry in the map may have.

**Comment by buksvdl** [comment]
ALL our properties classes are nested this way. Without the extended functionality there is no reason to pull in the lib. The need stays, so we will go the extra mile and add the missing recursion.

**Comment by philwebb** [comment]
@dgensert This issue remains open and is something we'd like to fix but we haven't been able to get to it yet. Please be respectful in your comments. We're a small team trying to deliver what we can, but we only have finite resources and a certain number of hours in the day.

**Comment by nosan** [comment]
I've been working on this issue for a while and have come up with some changes: https://github.com/spring-projects/spring-boot/compare/main...nosan:spring-boot:gh-9945

The proposed changes provide configuration property metadata support for binding to
`Map<String, RichType>` and `List<RichType>`. Consider the following example class:

<details>

```java

@ConfigurationProperties(prefix = "config")
public class RichProperties<T> {

	private final CustomList customList = new CustomList();

	private final CustomMap customMap = new CustomMap();

	@NestedConfigurationProperty
	private final List rawList = new ArrayList<>();

	@NestedConfigurationProperty
	private final List<?> listOfWildcard = new ArrayList<>();

	@NestedConfigurationProperty
	private final List<List<Person>> listOfList = new ArrayList<>();

	@NestedConfigurationProperty
	private final List<Map<String, Person>> listOfMap = new ArrayList<>();

	@NestedConfigurationProperty
	private final List<Person> list = new ArrayList<>();

	@NestedConfigurationProperty
	private final List<T> listOfUnresolvedGeneric = new ArrayList<>();

	@NestedConfigurationProperty
	private final Map rawMap = new LinkedHashMap<>();

	@NestedConfigurationProperty
	private final Map<String, ?> mapOfWildcard = new LinkedHashMap<>();

	@NestedConfigurationProperty
	private final Map<String, List<Person>> mapOfList = new LinkedHashMap<>();

	@NestedConfigurationProperty
	private final Map<String, Map<String, Person>> mapOfMap = new LinkedHashMap<>();

	@NestedConfigurationProperty
	private final Map<String, Person> map = new LinkedHashMap<>();

	@NestedConfigurationProperty
	private final Map<String, T> mapOfUnresolvedGeneric = new LinkedHashMap<>();

	// get;set
	public static class Person {

		private String name;

		@NestedConfigurationProperty
		private final List<Address> addresses = new ArrayList<>();

		// get;set

	}

	public static class Address {

		private String street;

		// get;set

	}

	public static class CustomMap extends LinkedHashMap<String, Person> {

	}

	public static class CustomList extends LinkedHashSet<Person> {

	}

}

```

</details>

The generated JSON metadata will be:
<details>

```json
{
  "groups": [
    {
      "name": "config",
      "type": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties"
    },
    {
      "name": "config.custom-list",
      "type": "org.springframework.boot.configurationsample.specific.RichProperties$CustomList",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getCustomList()"
    },
    {
      "name": "config.custom-list.[].addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.custom-map",
      "type": "org.springframework.boot.configurationsample.specific.RichProperties$CustomMap",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getCustomMap()"
    },
    {
      "name": "config.custom-map.*.addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.list",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getList()"
    },
    {
      "name": "config.list-of-list",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getListOfList()"
    },
    {
      "name": "config.list-of-list.[].[].addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.list-of-map",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getListOfMap()"
    },
    {
      "name": "config.list-of-map.[].*.addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.list-of-unresolved-generic",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getListOfUnresolvedGeneric()"
    },
    {
      "name": "config.list-of-wildcard",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getListOfWildcard()"
    },
    {
      "name": "config.list.[].addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.map",
      "type": "java.util.Map",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getMap()"
    },
    {
      "name": "config.map-of-list",
      "type": "java.util.Map",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getMapOfList()"
    },
    {
      "name": "config.map-of-list.*.[].addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.map-of-map",
      "type": "java.util.Map",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getMapOfMap()"
    },
    {
      "name": "config.map-of-map.*.*.addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.map-of-unresolved-generic",
      "type": "java.util.Map",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getMapOfUnresolvedGeneric()"
    },
    {
      "name": "config.map-of-wildcard",
      "type": "java.util.Map",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getMapOfWildcard()"
    },
    {
      "name": "config.map.*.addresses",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person",
      "sourceMethod": "getAddresses()"
    },
    {
      "name": "config.raw-list",
      "type": "java.util.List",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getRawList()"
    },
    {
      "name": "config.raw-map",
      "type": "java.util.Map",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties",
      "sourceMethod": "getRawMap()"
    }
  ],
  "properties": [
    {
      "name": "config.custom-list.[].addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.custom-list.[].name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    },
    {
      "name": "config.custom-map.*.addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.custom-map.*.name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    },
    {
      "name": "config.list-of-list.[].[].addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.list-of-list.[].[].name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    },
    {
      "name": "config.list-of-map.[].*.addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.list-of-map.[].*.name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    },
    {
      "name": "config.list.[].addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.list.[].name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    },
    {
      "name": "config.map-of-list.*.[].addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.map-of-list.*.[].name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    },
    {
      "name": "config.map-of-map.*.*.addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.map-of-map.*.*.name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    },
    {
      "name": "config.map.*.addresses.[].street",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Address"
    },
    {
      "name": "config.map.*.name",
      "type": "java.lang.String",
      "sourceType": "org.springframework.boot.configurationsample.specific.RichProperties$Person"
    }
  ],
  "hints": [],
  "ignored": {
    "properties": []
  }
}



```

</details>


I've used the prefix `*` for `Map` types and the prefix `[]` for `Collection` types. I
intentionally avoided using `*` for both to ensure the IDE can clearly distinguish between
`Map` and `Collection` types.


```java
class Type {

	String name;

}

// map.*.name
Map<String, Type> map;

// map-of-map.*.*.name
Map<String, Map<String, Type>> mapOfMap;

// list.[].name
List<Type> list;

// list-of-list.[].[].name
List<List<Type>> listOfList;

// list-of-map.[].*.name
List<Map<String, Type>> listOfMap;

// map-of-list.*.[].name
Map<String, List<Type>> mapOfList;


```

**Comment by renannprado** [comment]
@nosan I was preparing some configuration properties and then I faced this issue.

When the classes are nested, the generated `type` is `java.util.Map<java.lang.String,com.example.MyClass$MyRecord>`. So when I see only `java.util.Map` in your example, it doesn't look correct.

**Edit:**

As far as I can see, even if it's an inner class, the config metadata of `com.example.MyClass$MyRecord` will still not be properly generated.

**Comment by nosan** [comment]
> As far as I can see, even if it's an inner class, the config metadata of com.example.MyClass$MyRecord will still not be properly generated.

 `Map` or `List` fields/methods must be annotated with `@NestedConfigurationProperty` to signal to the annotation processor that it is a rich type and should be expanded; otherwise, there is no way to determine whether properties should be generated. For example, in `Map<String, Duration>`, `Duration` is not a simple (scalar) property like `java.lang.String`, but the annotation processor should not try to generate properties for it.

> When the classes are nested, the generated type is java.util.Map<java.lang.String,com.example.MyClass$MyRecord>. So when I see only java.util.Map in your example, it doesn't look correct.

Sorry, what is the example? Could you please point it out to me?

**Comment by renannprado** [comment]
@nosan I meant that in your example I see it generating `"type": "java.util.List"` instead of `"type": "java.util.List<com.company.Clazz">`.

Is there any workarounds for this? even if it means adding a few entries manually just to help the tooling figure out?

@philwebb is it realistic someone outside the spring team could contribute to get this issue fixed?

**Comment by philwebb** [comment]
> Is it realistic someone outside the spring team could contribute to get this issue fixed?

I think it's unlikely TBH. This one probably needs deep consideration from the team. I'll update the labels on the issue.

**Comment by renannprado** [comment]
@philwebb I'm very cautious in asking such questions, because we all know how open source is. By all means I'm not demanding anything. But do you have an idea when would have news about this issue and/or would labels be changed if the spring team starts to actively work on this?

Thanks for the quick reply btw.

**Comment by philwebb** [comment]
@renannprado The labels would change and the issue would be assigned to someone once we start work on it. I'll flag it for a team discussion on our next call since it's quite an old issue and there's not been much movement on it.

**Comment by renannprado** [comment]
@philwebb I just happen to remember about this issue and I saw that the `team-meeting` label has been removed. It would be really great to have this fixed (or at least moving it forward a little bit) although now with AI you can simply ask for the `additional-spring-configuration-metadata.json` to be generated.
